#!/bin/bash
workdir=$(pwd | awk -F/ '{print $(NF-3)}')
if [ "$workdir" != "dev" ];then
	echo "Seems like a wrong directory"
	exit
fi

language=$(pwd | awk -F/ '{print $(NF-2)}')
platform=$(pwd | awk -F/ '{print $(NF-1)}')
project=$(pwd  | awk -F/ '{print $(NF)}')
devdirprefix=/mnt/c/Users/VarunMohan/dev
buildtools="$devdirprefix"/buildtools/"$language"/"$platform"

compileserverip=192.168.2.149
compilerootprefix=/home/varun/coding
compileroot="$compilerootprefix"/"$language"/"$platform"

if [ `ip route get $compileserverip | grep via | wc -l` == 0 ];then
	compileserver=acer2
else
	compileserver=acer1
fi

#AVR Specific configurations
avrdude="$devdirprefix"/tools/avrdude
avrconf=C:\\Users\\VarunMohan\\dev\\tools\\avrdude\\avrdude.conf
##

if [ "$buildtools"/Makefile -nt Makefile ];then
	echo "Copying newer Makefile from buildtools."
	cp "$buildtools"/Makefile .
else
	echo "Makefile is uptodate. No need to copy."
fi

function fmake {
echo Project is "$project"
echo Syncing files with complie server : "$compileserver"
rsync -aPq --delete --exclude=".*" --exclude="tmp" --exclude="bin"  ../"$project" varun@"$compileserver":"$compileroot"
echo Running make on target
ssh  "$compileserver" "cd $compileroot/$project;mkdir -p tmp bin;make"
echo Copy binary back to us
rsync -aq  "$compileserver":"$compileroot"/"$project"/bin/"$project"* bin/
}

function fburnavr {
"$avrdude"/avrdude.exe -C"$avrconf" -v -patmega328p -carduino -PCOM3 -b115200 -D -Uflash:w:bin/"$project".hex:i
}

function fall {
	case "$platform" in
		avr)
			fmake
			fburnavr
			;;
	          *)
			fmake
			;;
	esac
}

if [ $# -eq 0 ]; then
        fall
else
        case "$1" in
                make)
                        fmake
                        ;;
                burn)
                        case "$platform" in
							avr)
								fburnavr
								;;
							  
							  *)
								;;
						esac
                        ;;
                   *)
                        echo Invalid Option
                        ;;
        esac
fi